### ISSUE TITLE
Custom 500 page

### ISSUE THREAD

**Issue by piotrrojek** [Unknwon/macaron#49]
Is there any way to add custom 500 page? Or any error page besides 404?

**Comment by ipfans** [comment]
You can use ```func (r *Router) NotFound(handlers ...Handler)``` to set default 404 page.

If you want to set custom 500 page, my solution is to define my own recovery middleware.

**Comment by Unknwon** [comment]
Hi @piotrrojek , as @ipfans said, [func (r *Router) NotFound(handlers ...Handler)](https://gowalker.org/github.com/Unknwon/macaron#Router_NotFound) can be used to set custom 404 page.

404 is easy to detect because it's on the router layer, but most of 500 is based on your handler logic, framework has no idea about it, and it often happens in the middle of handler logic.

Similiar solution to @ipfans , you can make a middleware/function/method to handle 500 page and call it whenever you need it.

For example, in Gogs, we use a custom method to show 500 page: https://github.com/gogits/gogs/blob/master/modules/middleware/context.go#L131

Hope helps!

**Comment by cgyy** [comment]
@Unknwon  您看看如果 handler可以返回error 就可以自定义500页面了， 这样实现业务逻辑的代码也会短很多。就行echo这样 https://github.com/labstack/echo

**Comment by Unknwon** [comment]
@cgyy This is a good idea, thanks your info!

**Comment by Unknwon** [comment]
Hi all, 

Right now you can trigger 500 page handling by:

```go
m.Get("/", func() error {
    return errors.New("this is an error")
})
```

So default 500 handler will be called.

If you want to use custom handler(s):

```go
m.InternalServerError(handler1, handler2, ...)
```

Be sure that you write response status 500 in **your last handler**.

But if there is no error, just return nil:

```go
m.Get("/", func() error {
    return nil
})
```

Feedbacks welcome!

**Comment by cgyy** [comment]
赞一个，这样逻辑代码会简洁很多！

**Comment by Unknwon** [comment]
@cgyy thanks for confirmation!

**Comment by cgyy** [comment]
你好，@Unknwon, 在实际使用中发现这样的问题:
```go
	m.Use(func(c *macaron.Context) error {
		c.Next()
		return errors.New("middle ware error")
	})

	m.Get("/", func() string {
		return "Hello world!"
	})

```
最后会输出 Hello world!middle ware error。
这种问题怎么解决比较好，是不是从业务逻辑上讲在middleware中，在Next执行后发生错误不应该return error 而是直接panic更好一点。
期待您的建议.

**Comment by Unknwon** [comment]
@cgyy 

I think your example does not explain well, from limited information, I think you should use `ctx.Written()` method to check if there are any thing has been written before you return error:

```go
  m.Use(func(c *macaron.Context) error {
        c.Next()

    if ctx.Written() {
        return nil
    }
        return errors.New("middle ware error")
    })
```

**Comment by cgyy** [comment]
好的，明白了，谢谢~

**Comment by Unknwon** [comment]
Close as implemented. :star:
