### ISSUE TITLE
reflect-ion

### ISSUE THREAD

**Issue by jfcg** [Unknwon/macaron#58]
Hi,
Did you have a chance to read
http://codegangsta.io/blog/2014/05/19/my-thoughts-on-martini/
https://github.com/zenazn/goji
Thx for gogs, it's great :)

**Comment by Unknwon** [comment]
Hi @jfcg ,

Yes, I've read that post long time ago. 

Quick answer is in my opinion, reflection is all good but relatively slow in Go.

Not sure you just want to show the article or you want to have discussion with me?

**Comment by jfcg** [comment]
i am not affiliated with any of those projects, just thinking loudly :)
would gogs be faster if you switch to goji ?

my two cents..

**Comment by Unknwon** [comment]
> would gogs be faster if you switch to goji ?

Probably not. When your business logic heavily depends on database, the speed of database transactions determine the performance of your web app. So I think as long as web framework router faster than DB transactions, there is no almost different/improvement for so-called "faster routing". 

I can be wrong based on my limited experiences with web app, and I'm only speaking in terms of Gogs project.

If you are do something like serving static resources, goji can be faster than using Macaron.

And one important thing to point out that as far as I see, people tend to cheat that they don't benchmark with advanced/complex regexp routing, all they have is optimized placeholder pattern matching or list based so-called [Pattern](https://godoc.org/github.com/zenazn/goji/web#Pattern). (still, I can be wrong since I haven't deeply read their source code)

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by otraore** [comment]
While your DB transactions are the most important bottleneck in any application, a fast http implementation such as [fasthttp](https://github.com/valyala/fasthttp) can make a difference. For example tech empowers benchmarks where fasthttp beats almost every other competing go implementation. [here](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=query&l=27wef3) both fasthttp and go std lib were using postgresql and doing the same transactions yet the fasthttp version was nearly 2x faster. It even went on going to beat all competing frameworks and languages (including languages like C, C++, Java, JavaScript, Ruby, Python etc etc) in data updates even though they were mainly using the same database [here](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=update). I'm not saying to rewrite gogs in fasthttp, or a framework like echo but just to clarify that the http server/framework/router can have an effect on performance. Especially when using reflection (which is why martini was discontinued). Side note: Besides being faster, fasthttp also is [easier on memory and other things](https://github.com/valyala/fasthttp#http-server-performance-comparison-with-nethttp). Have a nice day and thank you for creating gogs.
